<?php
/**
 * Diglin GmbH
 *
 * @category    Diglin
 * @package     Diglin_Username
 * @author      Sylvain Rayé <support@diglin.com>
 * @copyright   Copyright (c) 2008-2015 Diglin GmbH - Switzerland (http://www.diglin.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
use Diglin\Username\Model\Generate\Flag;

/* @var $block Diglin\Username\Block\Config\Form\Field\Generate.php */
?>
<script>
    require([
        'jquery',
        'prototype',
        'mage/backend/validation',
        'jquery/validate'
    ], function(jQuery){

        function enableSyncButton() {
            Form.Element.enable('generate_button');
            $('generate_button').removeClassName('disabled');
        }

        function disableSyncButton() {
            Form.Element.disable('generate_button');
            $('generate_button').addClassName('disabled');
        }

        function checkStatus() {
            u = new Ajax.PeriodicalUpdater('', '<?php /* @escapeNotVerified */ echo $this->getAjaxStatusUpdateUrl() ?>', {
                method:     'get',
                frequency:  5,
                loaderArea: false,

                onSuccess: function(transport) {
                    var response;

                    try {
                        response = JSON.parse(transport.responseText);
                        if (response.state == '<?php /* @escapeNotVerified */ echo Flag::STATE_RUNNING ?>'
                            && response.message
                        ) {
                            if ($('sync_span').hasClassName('no-display')) {
                                $('sync_span').removeClassName('no-display');
                                $('sync_message_span').update(response.message);
                            }

                        } else {
                            u.stop();
//                            $('sync_span').addClassName('no-display');
                            $('generate_process_spinner').addClassName('no-display');

                            if (response.state == '<?php /* @escapeNotVerified */ echo Flag::STATE_NOTIFIED ?>') {
                                if (response.message) {
                                    if ($('sync_span').hasClassName('no-display')) {
                                        $('sync_span').removeClassName('no-display');
                                    }
                                    $('sync_message_span').update(response.message);
                                }
                                if (response.has_errors) {
                                    enableSyncButton();
                                }
                            }
                        }
                    } catch (e) {
                        response = {};
                    }
                }
            });
        }

        jQuery('#generate_button').click(function () {

            if (!confirm('<?php echo $block->escapeJsQuote(__("Do you really want to create an username for customers who don't have one ?")); ?>')) {
                return;
            }

            params = {};

            new Ajax.Request('<?php /* @escapeNotVerified */ echo $block->getAjaxSyncUrl() ?>', {
                parameters:     params,
                loaderArea:     false,
                asynchronous:   true
            });

            window.setTimeout(checkStatus, 2011);
            disableSyncButton();
        });
    });
</script>

<?php echo $block->getButtonHtml(); ?><span class="sync-indicator no-display" id="sync_span"><img id="generate_process_spinner" alt="<?php echo __('Generate') ?>" style="margin:0 5px" src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/process_spinner.gif') ?>"/><span id="sync_message_span"></span></span>
